### ISSUE TITLE
please support Fail

### ISSUE THREAD

**Issue by gares** [coq-tactician/coq-tactician#1] opened 2020-09-10 15:53 UTC
It seems `Fail` is not working as expected.
```coq
Require Import Tactician.Ltac1.Record.
Example test_intro : True.
Proof.
Fail whatever. (* Error: the command did not fail *)
```
Whatever I write after `Fail` does not fail (even non existing tactics).
This makes the compilation of coq-elpi fail (since it contains a test suite using Fail).

**Comment by LasseBlaauwbroek** [comment] 2020-09-10 20:40
I am unable to reproduce your test on a fresh install with Coq `v8.11.2`. However, I can reproduce the failure to compile `coq-elpi` after Tactician has been installed. Are you also running Coq 8.11.2?

**Comment by LasseBlaauwbroek** [comment] 2020-09-11 00:13
Ah, it seems that only `coqc` is affected, not `coqtop` or `coqide`. This issue is due to some rather evil trickery with Coqs STM. I've now pushed a fix for it. Let me know if you have more problems.

I see that you want to combine Tacticians and Elphi's grammar? That should be interesting. I should note that the version currently in the opam repo is somewhat error prone (for example, don't use async processing). I'm hoping to do a proper 1.0 release in the next two months, with a much more stable version.

**Closed by LasseBlaauwbroek** 2020-09-11 00:13 UTC

**Comment by gares** [comment] 2020-09-11 05:48
I noticed async processing is broken, but I couldn't not understand why. If you need some help just ask on Zulip.

**Comment by LasseBlaauwbroek** [comment] 2020-09-11 05:50
The async processing is fixed in the version in the `experimental` branch. But I do not recommend you use that since it is rather slow and memory hungry.
